### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by ursm** [takkanm/esarch#1]
```
$ elixir -v
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:4:4] [async-threads:10]

Elixir 1.3.4
$ mix -v
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:4:4] [async-threads:10]

Mix 1.3.4
$ mix escript.install github github takkanm/esarch
** (Mix) Unexpected arguments.
Usage: mix escript.install <path or url>
```

**Comment by takkanm** [comment]
I fixed README.

https://github.com/takkanm/esarch#installation

Could you try it?

**Comment by ursm** [comment]
It did not work.

```
$ ghq get takkanm/esarch
$ cd -- /home/ursm/src/github.com/takkanm/esarch
$ mix script.install
Unchecked dependencies for environment dev:
* ex_doc (Hex package)
  the dependency is not available, run "mix deps.get"
* poison (Hex package)
  the dependency is not available, run "mix deps.get"
* httpoison (Hex package)
  the dependency is not available, run "mix deps.get"
** (Mix) Can't continue due to errors on dependencies

**Comment by takkanm** [comment]
🙇 

Colud you try `mix deps.get` before `mix escript.install`?

**Comment by takkanm** [comment]
```sh
$ mix deps.get
$ mix escript.build
$ mix escript.install
```

**Comment by ursm** [comment]
It appears to be installed. However, this error occurs when executed.

```
$ ~/.mix/escripts/esarch enishitech foo
** (FunctionClauseError) no function clause matching in Esarch.show_result/1
    (esarch) lib/esarch.ex:37: Esarch.show_result(%{"error" => "unauthorized", "message" => "Unauthorized"})
    (elixir) lib/kernel/cli.ex:76: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

How can I solve this?

**Comment by takkanm** [comment]
You should add esa token before search.

https://github.com/takkanm/esarch#setting

**Comment by ursm** [comment]
It worked, thank you!
